export const decoderLayouts = [
  { name: "Account", words: 1, state: false },
  { name: "Asset", words: 1, state: false },
  { name: "Node", words: 1, state: false },
  { name: "Limits", words: 1, state: false },
  { name: "Amount", words: 2, state: false },
  { name: "Balance", words: 2, state: true },
  { name: "AssetLiability", words: 2, state: false },
  { name: "AccountAsset", words: 2, state: false },
  { name: "HostAsset", words: 2, state: false },
  { name: "Bootstrap", words: 3, state: false },
  { name: "Allocation", words: 3, state: false },
  { name: "Allowance", words: 3, state: false },
  { name: "Custody", words: 3, state: true },
  { name: "AccountAmount", words: 3, state: false },
  { name: "HostAccountAsset", words: 3, state: false },
  { name: "Quote", words: 4, state: false },
  { name: "Transaction", words: 4, state: false },
  { name: "Position", words: 5, state: true },
  { name: "BalanceConstraints", words: 3, state: false },
  { name: "PositionConstraints", words: 4, state: false },
];
